// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"go-api-template/ent/job"
	"go-api-template/ent/jobapplication"
	"go-api-template/ent/user"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
)

// JobApplication is the model entity for the JobApplication schema.
type JobApplication struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// JobID holds the value of the "job_id" field.
	JobID uuid.UUID `json:"job_id,omitempty"`
	// ContractorID holds the value of the "contractor_id" field.
	ContractorID uuid.UUID `json:"contractor_id,omitempty"`
	// State holds the value of the "state" field.
	State jobapplication.State `json:"state,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the JobApplicationQuery when eager-loading is set.
	Edges        JobApplicationEdges `json:"edges"`
	selectValues sql.SelectValues
}

// JobApplicationEdges holds the relations/edges for other nodes in the graph.
type JobApplicationEdges struct {
	// Contractor holds the value of the contractor edge.
	Contractor *User `json:"contractor,omitempty"`
	// Job holds the value of the job edge.
	Job *Job `json:"job,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// ContractorOrErr returns the Contractor value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e JobApplicationEdges) ContractorOrErr() (*User, error) {
	if e.Contractor != nil {
		return e.Contractor, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "contractor"}
}

// JobOrErr returns the Job value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e JobApplicationEdges) JobOrErr() (*Job, error) {
	if e.Job != nil {
		return e.Job, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: job.Label}
	}
	return nil, &NotLoadedError{edge: "job"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*JobApplication) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case jobapplication.FieldState:
			values[i] = new(sql.NullString)
		case jobapplication.FieldCreatedAt, jobapplication.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		case jobapplication.FieldID, jobapplication.FieldJobID, jobapplication.FieldContractorID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the JobApplication fields.
func (ja *JobApplication) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case jobapplication.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				ja.ID = *value
			}
		case jobapplication.FieldJobID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field job_id", values[i])
			} else if value != nil {
				ja.JobID = *value
			}
		case jobapplication.FieldContractorID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field contractor_id", values[i])
			} else if value != nil {
				ja.ContractorID = *value
			}
		case jobapplication.FieldState:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field state", values[i])
			} else if value.Valid {
				ja.State = jobapplication.State(value.String)
			}
		case jobapplication.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				ja.CreatedAt = value.Time
			}
		case jobapplication.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				ja.UpdatedAt = value.Time
			}
		default:
			ja.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the JobApplication.
// This includes values selected through modifiers, order, etc.
func (ja *JobApplication) Value(name string) (ent.Value, error) {
	return ja.selectValues.Get(name)
}

// QueryContractor queries the "contractor" edge of the JobApplication entity.
func (ja *JobApplication) QueryContractor() *UserQuery {
	return NewJobApplicationClient(ja.config).QueryContractor(ja)
}

// QueryJob queries the "job" edge of the JobApplication entity.
func (ja *JobApplication) QueryJob() *JobQuery {
	return NewJobApplicationClient(ja.config).QueryJob(ja)
}

// Update returns a builder for updating this JobApplication.
// Note that you need to call JobApplication.Unwrap() before calling this method if this JobApplication
// was returned from a transaction, and the transaction was committed or rolled back.
func (ja *JobApplication) Update() *JobApplicationUpdateOne {
	return NewJobApplicationClient(ja.config).UpdateOne(ja)
}

// Unwrap unwraps the JobApplication entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (ja *JobApplication) Unwrap() *JobApplication {
	_tx, ok := ja.config.driver.(*txDriver)
	if !ok {
		panic("ent: JobApplication is not a transactional entity")
	}
	ja.config.driver = _tx.drv
	return ja
}

// String implements the fmt.Stringer.
func (ja *JobApplication) String() string {
	var builder strings.Builder
	builder.WriteString("JobApplication(")
	builder.WriteString(fmt.Sprintf("id=%v, ", ja.ID))
	builder.WriteString("job_id=")
	builder.WriteString(fmt.Sprintf("%v", ja.JobID))
	builder.WriteString(", ")
	builder.WriteString("contractor_id=")
	builder.WriteString(fmt.Sprintf("%v", ja.ContractorID))
	builder.WriteString(", ")
	builder.WriteString("state=")
	builder.WriteString(fmt.Sprintf("%v", ja.State))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(ja.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(ja.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// JobApplications is a parsable slice of JobApplication.
type JobApplications []*JobApplication
