// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Invoice is the predicate function for invoice builders.
type Invoice func(*sql.Selector)

// Job is the predicate function for job builders.
type Job func(*sql.Selector)

// JobApplication is the predicate function for jobapplication builders.
type JobApplication func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
